### ISSUE TITLE
BC break: zAdd does not support adding multiple members at once

### ISSUE THREAD

**Issue by umpirsky** [snc/SncRedisBundle#559] opened 2020-03-06 12:11 UTC
We notices this after upgrading `snc/redis-bundle (2.1.4 => 3.2.1)`.

In `2.1.4`:

```
$this->get('snc_redis.mydb')->zAdd('key', 1, 'item1', 2, 'item2');
```

Adds both members.

In `3.2.1`, same code only adds the first member.

**Comment by curry684** [comment] 2020-03-09 11:43
This is by definition not a BC break as it's a major version upgrade.

Also, `zAdd` is not our API but part of phpRedis. They may have inadvertently broken this behavior in their own latest upgrade as they were required to revise all parameters.

According to https://github.com/phpredis/phpredis#zadd it should work, if it doesn't in the latest phpRedis version you should file an issue there.

**Comment by umpirsky** [comment] 2020-03-09 12:10
I didn't upgrade phpRedis, I only updated this `snc/redis-bundle` from `2.1.4` to `3.2.1`.

In `2.1.4` this worked, in `3.2.1` it does not work. How can this be phpRedis issue?

**Comment by curry684** [comment] 2020-03-09 12:37
`$this->get('snc_redis.mydb')` returns an instance of `\Redis`, provided by phpRedis. This bundle only provides the integrates of phpRedis and Predis in a nice Symfony bundle. The call to `zAdd` and its parameters are on their end.

**Comment by curry684** [comment] 2020-03-09 12:39
Actually you may be using [Predis](https://packagist.org/packages/predis/predis) instead of phpRedis (this bundle can do both) but since Predis is unmaintained since 2016 you're advised to upgrade to phpRedis in that case.

**Comment by B-Galati** [comment] 2020-03-09 12:40
Could you show your config @umpirsky ?

**Comment by umpirsky** [comment] 2020-03-09 12:55
I use phpredis:

```yaml
snc_redis:
    clients:
        mydb:
            alias: mydb
            type: phpredis
            logging: false
            dsn: "redis:///var/run/db0.sock"
            options:
                profile: 4.2
                prefix: "myprefix:"
                read_write_timeout: 10
```

**Comment by curry684** [comment] 2020-03-09 13:13
Nope, doing it correctly:

https://github.com/snc/SncRedisBundle/blob/e48635a01888b7d6150f2f72c766fdc4a658cf9b/Client/Phpredis/Client.php#L1074-L1080

**Comment by B-Galati** [comment] 2020-03-09 13:31
@curry684 Yea that was my guess but the proxy class is not even activated with `logging: false` IIRC.

Also what's your phpredis version @umpirsky ?

**Comment by umpirsky** [comment] 2020-03-09 14:10
It's `5.1.1`. Thanks.

**Comment by umpirsky** [comment] 2020-03-11 18:08
Can we reopen this issue please?

**Comment by curry684** [comment] 2020-03-12 08:21
[I don't see a reason to](https://github.com/snc/SncRedisBundle/issues/559#issuecomment-596500427). `zAdd` is part of the phpredis API, not ours.

If you want to be 101% sure - do a `dump($this->get(get_class('snc_redis.mydb')))` somewhere in your controller. Given the information supplied that should return `\Redis`, meaning the issue is with phpredis.

**Comment by umpirsky** [comment] 2020-03-12 12:59
How do you explain same version (`5.1.1`) or phpredis works correctly with `snc/redis-bundle:2.1.4`, but not with `snc/redis-bundle:3.2.1`?

**Comment by B-Galati** [comment] 2020-03-12 14:11
I just tested it against `master` branch with our integration test and it works as expected.

With PHPRedis 3.1.6.

```php
$this->redis->del('key');
$this->redis->zAdd('key', 0, 'a', 0, 'b', 0, 'c');
dump($this->redis->zRange('key', 0, -1));
// ^ array:3 [
//   0 => "a"
//   1 => "b"
//   2 => "c"
// ]

$this->redis->del('key');
$this->redis->zAdd('key', 1, 'item1', 2, 'item2',0, 'item0');
dump($this->redis->zRange('key', 0, -1));
// ^ array:3 [
//   0 => "item0"
//   1 => "item1"
//   2 => "item2"
// ]
```

Could you setup a reproducer?

**Comment by umpirsky** [comment] 2020-03-12 15:49
Just run the same code with PHPRedis `5.1.1`.

**Comment by B-Galati** [comment] 2020-03-12 16:00
Run this code within your app, it will be the same thing.

**Comment by umpirsky** [comment] 2020-03-12 16:10
PHPRedis `5.1.1`, `snc/redis-bundle` `3.2.1`:

```
$this->redis->del('key');
$this->redis->zAdd('key', 0, 'a', 0, 'b', 0, 'c');
dump($this->redis->zRange('key', 0, -1));
// ^ array:3 [
//   0 => "a"
// ]

$this->redis->del('key');
$this->redis->zAdd('key', 1, 'item1', 2, 'item2',0, 'item0');
dump($this->redis->zRange('key', 0, -1));
// ^ array:3 [
//   1 => "item1"
// ]
```

**Comment by curry684** [comment] 2020-03-12 16:16
So ok, phpredis 5.1.1 has a bug apparently. Now goto https://github.com/snc/SncRedisBundle/issues/559#issuecomment-596478158

**Comment by umpirsky** [comment] 2020-03-12 16:46
No, because:

PHPRedis `5.1.1`, `snc/redis-bundle` `2.1.4`:

```
$this->redis->del('key');
$this->redis->zAdd('key', 0, 'a', 0, 'b', 0, 'c');
dump($this->redis->zRange('key', 0, -1));
// ^ array:3 [
//   0 => "a"
//   1 => "b"
//   2 => "c"
// ]

$this->redis->del('key');
$this->redis->zAdd('key', 1, 'item1', 2, 'item2',0, 'item0');
dump($this->redis->zRange('key', 0, -1));
// ^ array:3 [
//   0 => "item0"
//   1 => "item1"
//   2 => "item2"
// ]
```

**Comment by curry684** [comment] 2020-03-12 18:57
Ok now it gets interesting 😄

**Comment by B-Galati** [comment] 2020-03-13 06:58
Could you replace this line https://github.com/snc/SncRedisBundle/blob/e3b533d1bd67b5ebe7c18279722020a3410efcbe/DependencyInjection/SncRedisExtension.php#L301 by `$phpredisDef->setLazy(false);`

Is the issue still occurs?

**Comment by umpirsky** [comment] 2020-03-13 12:04
That solves the issue.

**Comment by curry684** [comment] 2020-03-14 00:46
@Ocramius can you have a look at this?

**Comment by Ocramius** [comment] 2020-03-14 02:19
@curry684 I suggest dumping the generated proxies (you can dump a production container and look at the generated files) and checking if there's a mismatch in argument definitions.

To me, it looks like phpredis doesn't expose the variadic arguments correctly (to reflection)

**Comment by B-Galati** [comment] 2020-03-14 08:06
Could it be the version of the Symfony proxy manager bridge?

**Comment by curry684** [comment] 2020-03-14 14:47
I vaguely remember an issue in phpredis that the internal PHP API doesn't expose variadics or something, and that's why they don't declare them like that... not remotely sure though. I agree it's on their end though.

**Comment by Ocramius** [comment] 2020-03-14 15:26
@B-Galati unlikely: variadics have been part of ProxyManager for a looooooooooooong time.

I suggest checking what the reflection API of phpredis reports. There's an ongoing effort to fix internal type definitions in PHP 8.0, so I'm sure many have tried figuring out this same problem for other APIs.

**Comment by curry684** [comment] 2020-03-16 07:50
Let's ask @yatsukhnenko to chip in on this on behalf of the phpredis team. The only alternative we have on our end is to completely disable lazy loading which kinda defeats the purpose.

**Comment by B-Galati** [comment] 2020-03-16 09:00
So yea lazy PHPRedis connection was enabled from version `2.1.5` which explains why you got no issue with `2.1.4` @umpirsky.

Like you said @curry684, we had a similar issue: see #442 and phpredis/phpredis#1374.

**Comment by yatsukhnenko** [comment] 2020-03-16 14:48
@curry684 looks like we have invalid arginfo  for zadd method. I'll fix it today and it will be a part of upcoming bugfix release

**Comment by curry684** [comment] 2020-03-17 12:48
Thank you @yatsukhnenko I see https://github.com/phpredis/phpredis/commit/a8e2b021f9eb51ad3ed0cc89064e2f004c56f8ba should fix it.

Closing this here now.

**Closed by curry684** 2020-03-17 12:48 UTC

**Comment by umpirsky** [comment] 2020-03-17 13:22
@yatsukhnenko I guess 5.2.1 will include this fix?

**Comment by michael-grunder** [comment] 2020-03-18 22:00
Hi, @umpirsky another phpredis developer here.  This change will be in phpredis 5.2.1 (tagging [5.2.1RC1](https://github.com/phpredis/phpredis/tree/release-5.2.1RC1) and uploading to PECL tomorrow morning).

Cheers!
Mike
