### ISSUE TITLE
Exception on connection are not catched by Symfony

### ISSUE THREAD

**Issue by jacquelotjeff** [snc/SncRedisBundle#490] opened 2019-01-16 15:23 UTC
Global informations : 
```yaml
sncRedisBundle version : 2.1.7 
Symfony version : v3.4.20
```

In dev environment, when the connection to the server is wrong, we can see this message : 

<img width="1095" alt="capture d ecran 2019-01-16 a 16 09 14" src="https://user-images.githubusercontent.com/11046841/51257944-18567f00-19a9-11e9-96f9-9cd41f1f07f3.png">

In production environment, we have a blank page and it not the good behaviour (need to show the 500 page template).

**Comment by B-Galati** [comment] 2019-01-16 15:34
Hello and thanks for reporting!

It looks like the host `redis-host` cannot be resolved. Are you sure this domain is available from your server ?

Regarding the blank page, it does not relate to this bundle. It's something that should be configured on your HTTP server or Symfony (https://symfony.com/doc/current/controller/error_pages.html).

In any case. I am closing this issue as I cannot see anything that can be fixed on the bundle.
Let me know if anything is not clear.

**Closed by B-Galati** 2019-01-16 15:34 UTC

**Comment by jacquelotjeff** [comment] 2019-01-16 16:11
Hello @B-Galati, 

Thanks for your answer. 
Sorry if I was not clear enough.

I know that the host cannot be resolved. I manually modified the host dsn to generate the error.

I have already a custom 500 page error like in your link (works well with others errors in my Application).

When the connection is wrong in SncRedisBundle, the error should be handled by Symfony (it is not the case, please try it).

I hope to be more clear this time ...

**Comment by B-Galati** [comment] 2019-01-16 16:19
IMHO the problem is not on the bundle.

Try to call `php_network_getaddresses` and you should have the same exact behavior.

**Comment by jacquelotjeff** [comment] 2019-01-16 16:33
The address `redis-host` is not correct (I know that).
In production environment, we can lost the connection to the redis server, so, in our application, this generate an error 500.

Let's take an other example (in production environment **not development**) : 
If my Symfony application fails to reach my mongodb server, I can see my custom error 500 page. So everything is fine.

However, if my Symfony application fails to reach redis, I can see a blank page instead of my custom error 500 page.

Can you check that on your side ?

**Comment by B-Galati** [comment] 2019-01-16 20:02
That's not needed IMHO. Please try to call `getaddrinfo` anywhere with a wrong domain name to see what is happening with the error page.

**Comment by B-Galati** [comment] 2019-01-16 20:15
You can try to install `symfony/proxy-manager-bridge` to see if the issue still continues. It could be because the error happened during service instantiation. I am not sure.

**Comment by jacquelotjeff** [comment] 2019-01-17 16:39
I have tested to install `symfony/proxy-manager-bridge` but the issue still continues.

Did you test it on your side ?
