### ISSUE TITLE
profiler_storage not working with Symfony 4

### ISSUE THREAD

**Issue by Teaxtor** [snc/SncRedisBundle#461] opened 2018-10-02 11:38 UTC
Hey all,

today I tried using the profiling storage feature from the snc redis bundle like this:
```yaml
snc_redis:
    clients:
        profiler:
            type: phpredis
            alias: profiler
            dsn: redis://%redis_host_profiler%/3
            logging: false
    profiler_storage:
        client: profiler
        ttl: 86400
```
But somehow still the FileProfilerStorage from Symfony got used when I debugged. After explicitly overwriting the service, it works:
```yaml
snc_redis:
    clients:
        profiler:
            type: phpredis
            alias: profiler
            dsn: redis://%redis_host_profiler%/3
            logging: false

services:
    profiler.storage:
        class: Snc\RedisBundle\Profiler\Storage\RedisProfilerStorage
        arguments:
            - '@snc_redis.profiler'
            - 86400
```

Is it possible, that the latest changes in Symfony 4 broke the overwriting mechanism you used, or did I miss anything? :S

I'm using Symfony 4.1.2 with Snc/Redis 2.1.4

Best,

Sebastian

**Comment by rpkamp** [comment] 2018-11-05 19:07
Not sure why that won't work for you. It works fine for me on Symfony 4.1.6 with snc/redis 2.1.7

Maybe try updating to those versions, or hard deleting the cache (`rm -rf /paht/to/your/symfony/project/var/cache`) and try again?

**Comment by curry684** [comment] 2019-02-20 13:23
Just tried to reproduce this in Symfony 4.2.3 with 3.0.0-RC2. Added following file to `config/packages/dev/snc_redis.yaml`:
```
snc_redis:
    clients:
        profile:
            type: phpredis
            alias: profiler
            dsn: redis://redis/5
    profiler_storage:
        client: profiler
        ttl: 86400
```
On first 5 it started gathering profiles in Redis instead of file and everything was still ok.

Therefore closing this bug.

**Comment by Amunak** [comment] 2019-03-02 12:24
So I actually have the same issue. I have basically the same configuration as in the first comment, and while the profiler data *does save* into the Redis cache, **the index - when retreived - always contains only a single result** (the first one). The result is that when you go to `/_profiler`, there is only a single "result" instead of all the profiler data (profiles?).

I cross-checked with Redis: when I run `redis:6379> MGET sf_prof_index` I can see all the results:
```
"s:96:\"a7d5b5\t10.10.10.20\tGET\thttp://example.com/route/retail-page\t1551528566\t\t200\n\";s:102:\"855fd3\t10.10.10.20\tGET\thttp://example.com/route/photogallery-page\t1551528569\t\t200\n\";s:95:\"c653eb\t10.10.10.20\tGET\thttp://example.com/route/media-page\t1551528571\t\t200\n\";s:95:\"53ed7d\t10.10.10.20\tGET\thttp://example.com/route/media-page\t1551528622\t\t200\n\";s:94:\"f79424\t10.10.10.20\tGET\thttp://example.com/route/404\t1551528623\t263c4e\t200\n\";s:88:\"263c4e\t10.10.10.20\tGET\thttp://example.com/route/404\t1551528623\t\t404\n\";s:89:\"2d850a\t10.10.10.20\tGET\thttp://example.com/route/novinky\t1551528627\t\t404\n\";s:81:\"d47f07\t10.10.10.20\tGET\thttp://example.com/route\t1551528636\t\t200\n\";s:94:\"ed6b6a\t10.10.10.20\tGET\thttp://example.com/route/care-page\t1551528638\t\t200\n\";s:81:\"af78dd\t10.10.10.20\tGET\thttp://example.com/route\t1551528640\t\t200\n\";s:101:\"68ea2d\t10.10.10.20\tGET\thttp://example.com/route/asd/charmant\t1551528641\t\t200\n\";"
```


But they don't even hit the `\Snc\RedisBundle\Profiler\Storage\RedisProfilerStorage::getValue` method. I added a dump there:

```php
    protected function getValue($key, $serializer = self::REDIS_SERIALIZER_NONE)
    {
        $value = $this->redis->get($key);

        if ($key === $this->getIndexName()) {
            var_dump($value);
        }

        if ($value && (self::REDIS_SERIALIZER_PHP === $serializer)) {
            $value = unserialize($value);
        }

        return $value;
    }
```

And that only shows the first result: `string(96) "a7d5b5 10.10.10.20 GET http://example.com/some/route 1551528566 200 " `

**Comment by curry684** [comment] 2019-03-04 09:50
I'll see if I have time to retest more thoroughly.

**Comment by starred-gijs** [comment] 2019-05-02 15:09
I can confirm it still works for me
SF 4.2.7, PHP 7.1.16, snc/redis-bundle 2.1.9, Redis 5.0.3

**Closed** 2019-10-18 14:56 UTC
Labels: bug

**Comment by B-Galati** [comment] 2019-10-18 14:58
With the next release (3.2.0), this feature will be disabled automatically if you are using Symfony 4.4.

>As the profiler must only be used on non-production servers, the file storage is more than enough and no other implementations will ever be supported.

**Comment by ottaviano** [comment] 2021-01-27 14:53
Hi, we have used RedisProfilerStorag with Sf 3.4 and it significantly improved the dev performances (specially on macos + docker + nfs file sharing, because it reduce write/read on filesystem).
Now, we are on Sf 4.4 and this storage is disabled, but we can easily activate it again by respecting `ProfilerStorageInterface` signatures.
Is there a particular reason to deactivate RedisStorage on 4.4? Maybe this storage should be a part of another package instead?

**Comment by starred-gijs** [comment] 2021-01-27 15:22
> As the profiler must only be used on non-production servers, the file storage is more than enough and no other implementations will ever be supported.

Symfony does not support it anymore. Obviously you may implement this feature in another package.

**Comment by ottaviano** [comment] 2021-01-27 15:34
what do you mean by "not support it anymore"? Sf provides an interface (`ProfilerStorageInterface`) to allow us to override the storage as we want. But this interface has become `@internal` - is that what you mean by "not support it anymore"?
  
If I fix signatures issues (return typehints) on `RedisProfilerStorage` class it works well on Sf 4.4

**Comment by starred-gijs** [comment] 2021-01-27 15:37
That Symfony team might decide to drop that interface in a future version.

> If I fix signatures issues (return typehints) on RedisProfilerStorage class it works well on Sf 4.4
Im not the maintainer of this package, nor do I use RedisProfilerStorage anymore, so I cant say if that will be merged or not.

**Comment by B-Galati** [comment] 2021-01-27 20:26
More information here: https://github.com/snc/SncRedisBundle/pull/543#issue-329729525.

>As per Symfony:
>
>>    This interface exists for historical reasons. The only supported
>>    implementation is FileProfilerStorage.
>>    As the profiler must only be used on non-production servers, the file storage
>>    is more than enough and no other implementations will ever be supported.

**Comment by ottaviano** [comment] 2021-01-28 09:59
thanks Benoit 👍
