### ISSUE TITLE
RedisBaseCommand extends ContainerAwareCommand gives deprecated mesage

### ISSUE THREAD

**Issue by pouyana** [snc/SncRedisBundle#480] opened 2018-12-11 10:11 UTC
Hi upon upgrading to Symfony 4.2 I get this deprecation notice.

The "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" class is deprecated since Symfony 4.2, use "Symfony\Component\Console\Command\Command" with dependency injection instead.

**Comment by pouyana** [comment] 2018-12-11 11:33
I looked at the code, In the master version it is fixed,

https://github.com/snc/SncRedisBundle/blob/master/Command/RedisBaseCommand.php#L26

but I assume it is not backward compatible with the 2.x and 3.x Symfony, so it is not pushed to 2.x version of the bundle. I can try dependency injection but I am not sure if it works with 2.x and 3.x Symfony...

**Comment by B-Galati** [comment] 2018-12-11 12:01
Command as a service looks like to be available since 2.7 so I agree with @pouyana and thus no need to do anything try to release v3 of this bundle when we can.

**Comment by adiq** [comment] 2018-12-11 14:40
Looking forward for v3. Let me know if you'll need any help on this one 😄

**Comment by curry684** [comment] 2018-12-11 20:11
Due to how deprecation works it's not possible for us to both support old versions of Symfony and fix every deprecation in the newer versions. For this reason it is considered acceptable if libraries cause some deprecation warnings (Doctrine currently causes tons actually running up to their 3.x transition).

If it is causing issues in strict CI testing consider using the `WEAK_VENDORS` constant value in the Symfony Deprecations Helper which was designed to mitigate this issue, as it breaks on deprecations in your own code and allows them in vendor-supplied code.

As you confirm this is fixed in 3.x and 2.x will never be forward compatible with Symfony 5 where the deprecation will really break there actually is no issue to be fixed   😉

**Closed by curry684** 2018-12-11 20:11 UTC

**Comment by curry684** [comment] 2018-12-11 20:13
Reference https://symfony.com/doc/current/components/phpunit_bridge.html#making-tests-fail on how to configure the deprecations helper.

**Comment by B-Galati** [comment] 2018-12-11 20:20
@adiq See #452 to catch up on what needs to be done for v3.
